"""storage unit name is unique

Revision ID: 62f6b5af6e14
Revises: f02eef3814e9
Create Date: 2025-01-28 17:42:06.454158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f6b5af6e14'
down_revision: Union[str, None] = 'f02eef3814e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'storage_unit', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storage_unit', type_='unique')
    # ### end Alembic commands ###
